name: 机场脚本更新

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  run-script-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: 
        pip install requests
        pip install base64
        pip install json
        pip install pyaes
        pip install binascii

    - name: 移除旧存档
      run: rm -f trojan.txt

    - name: 运行py脚本
      run: python  trojan.py > trojan.txt
