name: 机场节点

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依赖
      run: |
        # 各种模块
        pip install pyaes
        pip install requests
        pip install bs4


    - name: 删除txt文件（如果存在的话）
      run: rm -f vpn/txt/trojan.txt || true
           rm -f vpn/txt/ss.txt || true
           rm -f vpn/txt/vpn.txt || true
           rm -f vpn/txt/fast.txt || true
           rm -f vpn/txt/more.txt || true

      
    - name: 运行并输出结果v2    #很多节点，不太好用
      run: python vpn/py/v2.py > vpn/txt/v2.txt
    - name: 运行并输出结果ss
      run: python vpn/py/ss.py > ss.txt
    - name: 运行并输出结果trojan
      run: python vpn/py/trojan.py > trojan.txt


    - name: 创建合并文本vpn
      run: touch vpn/txt/vpn.txt
    - name: 创建合并文本fast
      run: touch vpn/txt/fast.txt


    # vpn节点最全，fast连通性测试最快（最少节点）
    - name: 合并结果vpn
      run: cat ss.txt trojan.txt v2.txt > vpn/txt/vpn.txt
    - name: 合并结果fast
      run: cat ss.txt trojan.txt > vpn/txt/fast.txt
           
    - name: Commit and push if there are changes
      run: |
        git init
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add vpn/txt/vpn.txt
        git add vpn/txt/fast.txt
        git add vpn/txt/v2.txt
        git commit -m "vpn/txt/vpn.txt" "vpn/txt/fast.txt" "vpn/txt/v2.txt" || exit 0
        git push
