name: 机场节点

on:
  schedule:
    - cron: "0 */6 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依赖
      run: |
        # 各种模块
        pip install pyaes
        pip install requests
        pip install bs4


    #- name: 重新创建合并文本
    #  run: |
    #    touch vpn/txt/vpn.txt
    #    touch vpn/txt/fast.txt
    #    touch vpn/txt/v2.txt


    - name: 删除vpn文件
      run: |
        rm -f vpn/txt/vpn.txt || ture
        rm -f vpn/txt/fast.txt || ture
        rm -f vpn/txt/v2.txt || ture
        

    - name: 运行并输出结果v2    #很多节点，不太好用
      run: |
        python vpn/py/v2.py > vpn/txt/v2.txt
        python vpn/py/ss.py > vpn/txt/ss.txt
        python vpn/py/trojan.py > vpn/txt/trojan.txt

        
    - name: 合并结果vpn
      run: |
        cat vpn/txt/ss.txt vpn/txt/trojan.txt vpn/txt/v2.txt > vpn/txt/vpn.txt
        cat vpn/txt/ss.txt vpn/txt/trojan.txt > vpn/txt/fast.txt
        rm -f vpn/txt/trojan.txt
        rm -f vpn/txt/ss.txt
        date > vpn/txt/vpn.txt
        date > vpn/txt/fast.txt
        date > vpn/txt/v2.txt


    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if [[ `git status --porcelain` ]]; then
          git commit -m "Update VPN files" && git push
        else
          echo "No changes to commit."
        fi
