name: 机场节点

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: 依赖
      run: |
        # 如果您的脚本需要额外的依赖，可以在这里安装
        # 例如: 
        pip install pyaes
        pip install requests

    # - name: 运行py脚本
    #  run: python trojan.py > trojan.txt
    #       python ./vpn/py/ss.py > ./vpn/txt/trojan.txt

    - name: 删除trojan.txt文件（如果存在的话）
      run: rm -f ./vpn/txt/trojan.txt || true
           rm -f ./vpn/txt/ss.txt || true
           rm -f ./vpn/txt/vpn.txt || true
      
    - name: 运行并输出结果
      run: python ./vpn/py/trojan.py > ./vpn/txt/trojan.txt
           python ./vpn/py/ss.py > ./vpn/txt/ss.txt
           
    - name: 合并结果
      run: cat ./vpn/txt/trojan.txt ./vpn/txt/ss.txt > vpn.txt
           
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add  ./vpn/txt/vpn.txt
        git commit -m "Update trojan.txt with latest results" || exit 0
        git push
